# Generated by Django 3.1.2 on 2020-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='instructor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
