# Generated by Django 3.1.2 on 2020-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
